FROM python:3.10-slim
LABEL maintainer = "Shubhankar"
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 5000
ENV APP_ENV = production
CMD ["python", "app.py"]
