apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 38d04f18037ecaab6377560be475248c508b8376573f38d01ad3e89c6daa8d37
    cni.projectcalico.org/podIP: 10.10.171.68/32
    cni.projectcalico.org/podIPs: 10.10.171.68/32
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Pod","metadata":{"annotations":{},"name":"quota-mem-cpu-demo","namespace":"resourcequota"},"spec":{"containers":[{"image":"nginx","name":"quota-mem-cpu-demo-ctr","resources":{"limits":{"cpu":"800m","memory":"800Mi"},"requests":{"cpu":"400m","memory":"600Mi"}}}]}}
  creationTimestamp: "2026-03-04T08:25:11Z"
  name: quota-mem-cpu-demo
  namespace: resourcequota
  resourceVersion: "25208"
  uid: a61f7d81-8037-4a14-9814-b54143b62cf0
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: quota-mem-cpu-demo-ctr
    resources:
      limits:
        cpu: 800m
        memory: 800Mi
      requests:
        cpu: 400m
        memory: 600Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-mwz64
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: worker
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-mwz64
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-03-04T08:25:18Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-03-04T08:25:11Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-03-04T08:25:18Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-03-04T08:25:18Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-03-04T08:25:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://76fce9f3b245b3e9b2f2f92d83bd517dc8c15948e9fe2d75c9b6df37d416dbb8
    image: docker.io/library/nginx:latest
    imageID: docker.io/library/nginx@sha256:0236ee02dcbce00b9bd83e0f5fbc51069e7e1161bd59d99885b3ae1734f3392e
    lastState: {}
    name: quota-mem-cpu-demo-ctr
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-03-04T08:25:17Z"
  hostIP: 172.31.20.161
  hostIPs:
  - ip: 172.31.20.161
  phase: Running
  podIP: 10.10.171.68
  podIPs:
  - ip: 10.10.171.68
  qosClass: Burstable
  startTime: "2026-03-04T08:25:11Z"
